### ISSUE TITLE
Incluir opção para ler bases anteriores do 156

### ISSUE THREAD

**Issue by tayana-melo** [CodeForCuritiba/ds-curitiba-dados-abertos#10]

**Comment by joepreludian** [comment]
Hey Tay. Por favor, você poderia descrever com mais detalhes como você gostaria que fosse feito essa história? Obrigado.

**Comment by tayana-melo** [comment]
Para maximizar o impacto das analises de dados é necessário analisar revisistar as bases históricos. Importante poder analisar o passado, para insights para o futuro. Para mim, seria legal, se eu pudesse correlacionar várias bases, brincar com os anos e meses, poder integrar, dividir, separar etc.. Entendo que é legal automatizar para a última base, a mais atualizadas. Porém, você precisa ter bases comparativas, para entender os comportamentos. Obrigada pela paciência.

**Comment by tayana-melo** [comment]
O kit, já puxa a última base, deveria ter um código de decisão qual base (ano,mês) importar.

**Comment by joepreludian** [comment]
@tayana-melo eu criei a issue em outro projeto com essa demanda que servirá para todas as iniciativas de datasource; https://github.com/CodeForCuritiba/curitiba-dados-abertos/issues/1

Assim que finalizar o ticket lá eu crio um ajuste para você conseguir importar aqui sem problemas;

**Comment by joepreludian** [comment]
Alterações finalizadas com sucesso. Favor verifique o arquivo do 156 com um exemplo baixando bases antigas. =)

https://github.com/CodeForCuritiba/ds-curitiba-dados-abertos/blob/master/estudos_156.ipynb

Em caso de dúvidas, reabra essa issue.
